import type { Metadata } from "next";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { AllStoresProvider } from "@/providers/AllStoresProvider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Header } from "@/components/layout/Header/Header";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const locale = await getLocale();

    return (
        <html lang={locale} suppressHydrationWarning>
            <body>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <NextIntlClientProvider>
                        <AllStoresProvider>
                            <QueryProvider>
                                <Header />
                                <main className="h-[calc(100vh-68px)] ">
                                    <NuqsAdapter>{children}</NuqsAdapter>
                                </main>
                            </QueryProvider>
                        </AllStoresProvider>
                    </NextIntlClientProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
